run_user: vagrant
docker_ip: "172.17.42.1"

postgres_user: web_test
postgres_database: web_test
postgres_password: '12345'
postgres_password_md5: 'md5f813067c8afde388f4a1d59c79cebfe7'
postgres_data: /volumes/postgres_data
postgres_replication_user: replication
postgres_replication_password: replication_password
postgres_master_dns: "postgres-master.service.consul"

postgres_master_health_check: "nc -z -w5 {{ postgres_master_dns }} 5432"


consul_bootstrap_expect: 3
consul_servers:
  - "172.20.20.10"
  - "172.20.20.11"
  - "172.20.20.12"

consul_watches:
  - type: service
    service: postgres-master
    handler: "NODE_PATH=/usr/lib/node_modules node --harmony {{ consul_config_base_dir }}/handlers/postgres_master_failover.sh"
