- hosts: all
  gather_facts: yes

  vars:
    run_user: vagrant
    n1_ip: "172.20.20.10"
    n2_ip: "172.20.20.11"
    docker_ip: "172.17.42.1"
    consul_data_dir: "/var/tmp/consul"

    postgres_user: web_test
    postgres_password: 12345

  roles:
    # - { role: angstwad.docker_ubuntu, tags: [docker,n1,n2], become: yes }

  tasks:
    # - include: common.yml

    - template:
       src: templates/n1.consul.upstart.conf.j2
       dest: /etc/init/consul.conf
      become: yes
      tags: [upstart, consul, n1]

    - template:
       src: templates/n2.consul.upstart.conf.j2
       dest: /etc/init/consul.conf
      become: yes
      tags: [upstart, consul, n2]

    - template:
       src: templates/n1.registrator.upstart.conf.j2
       dest: /etc/init/registrator.conf
      become: yes
      tags: [upstart, registrator, n1]

    - template:
       src: templates/n2.registrator.upstart.conf.j2
       dest: /etc/init/registrator.conf
      become: yes
      tags: [upstart, registrator, n2]

    - template:
       src: templates/n1.postgres.upstart.conf.j2
       dest: /etc/init/postgres.conf
      become: yes
      tags: [upstart, postgres, n1]

    - template:
       src: templates/n2.postgres.upstart.conf.j2
       dest: /etc/init/postgres.conf
      become: yes
      tags: [upstart, postgres, n2]
