- hosts: all
  gather_facts: yes

  vars:
    run_user: vagrant
    n1_ip: "172.20.20.10"
    n2_ip: "172.20.20.11"
    docker_ip: "172.17.42.1"
    consul_data_dir: "/var/tmp/consul"

    postgres_user: web_test
    postgres_database: web_test
    postgres_password: '12345'
    postgres_password_md5: 'md5f813067c8afde388f4a1d59c79cebfe7'
    postgres_data: /volumes/postgres_data
    postgres_replication_user: replication
    postgres_replication_password: replication_password
    postgres_master_ip: "{{ n1_ip }}"

    pgpool_data: /etc/pgpool2

  roles:
    # - { role: angstwad.docker_ubuntu, tags: [docker,n1,n2], become: yes }

  tasks:
    # - include: common.yml
    # - include: upstart.yml
    - include: pgpool.yml


