- hosts: all
  gather_facts: yes

  vars:
    run_user: vagrant
    n1_ip: "172.20.20.10"
    n2_ip: "172.20.20.11"
    docker_ip: "172.17.42.1"
    consul_data_dir: "/var/tmp/consul"

    postgres_user: web_test
    postgres_database: web_test
    postgres_password: 12345
    postgres_data: /volumes/postgres_data
    postgres_replication_user: replication
    postgres_replication_password: replication_password
    postgres_master_ip: "{{ n1_ip }}"

  roles:
    # - { role: angstwad.docker_ubuntu, tags: [docker,n1,n2], become: yes }

  tasks:
    # - include: common.yml
    - include: upstart.yml
    - include: postgres.yml
      tags: [n1]
      vars:
        role: master
        master_ip: "{{ n1_ip }}"
        slave_ip: "{{ n2_ip }}"

    # - postgresql_db: name={{postgres_user}}
    #   tags: [n1]


